name: OpenaiGPTLLM
# model_id: gpt-3.5-turbo
model_id: gpt-4o-mini
api_key: ${env| custom_openai_key, openai_api_key}
endpoint: ${env| custom_openai_endpoint, https://api.openai.com/v1}
temperature: 1.0
max_tokens: 8192
response_format: json_object
