name: Conclude
llm: ${sub|text_res}
prompts:
  - role: system
    template: examples/general_dnc/agent/conclude/sys_prompt.prompt
  - role: user
    template: examples/general_dnc/agent/conclude/user_prompt.prompt
output_parser: 
  name: StrParser